Import( 'env' )

objs = []
env.Move_head( [ '#./moon_code/include_%s/moon_common.h' % ( env['MOON_TARGET'] ) ], [ 'moon_common.h' ] )
env.Move_head( [ '#./moon_code/include_%s/moon_interface.h' % ( env['MOON_TARGET'] ) ], [ 'moon_interface.h' ] )
env.Move_head( [ '#./moon_code/include_%s/moon_pipe.h' % ( env['MOON_TARGET'] ) ], [ 'moon_pipe.h' ] )
env.Move_head( [ '#./moon_code/include_%s/common_interfaces.h' % ( env['MOON_TARGET'] ) ], [ 'common_interfaces.h' ] )

#obj = env.Object( 'moon_max_min_heap_%s' % env[ 'MOON_TARGET' ], 'moon_max_min_heap.c' )
#objs.append( obj )
obj = env.Object( 'moon_avltree_%s' % env[ 'MOON_TARGET' ], 'moon_avltree.c' )
objs.append( obj )
obj = env.Object( 'moon_pipe_%s' % env[ 'MOON_TARGET' ], 'moon_pipe.c' )
objs.append( obj )

Return( 'objs' )

