Import( 'env' )

obj = []
cur_env = env.Clone()
def make_head( source, target, env, for_signature):
	return 'cp %s %s' % ( source[0], target[0] )

bld = Builder( generator = make_head )
cur_env.Append( BUILDERS = { 'Foo' : bld } )
cur_env.Foo( '#./moon_code/include_%s/moon_common.h' % ( env['MOON_TARGET'] ), [ 'moon_common.h' ] )
Return( 'obj' )
