#coding:utf-8

Import( 'env' )

#test avl_tree
env.Program( 'avl_test.c' )
env.Move_head( 'avl_cmd.txt', '../test/avl_cmd.txt' )
env.Move_head( 'avl_result.txt', '../test/avl_result.txt' )
env.Move_head( 'avl.sh', '../test/avl.sh' )
#测试大小端转化
env.Program( 'convert_test.c' )
#测试moon_interface
env.Program( [ 'interface_main.c', 'interface_test1.c' ] )
#测试moon_pipe
env.Program( 'pipe_test.c' )
env.Move_head( 'pipe_seq.sh', '../test/pipe_seq.sh' )
env.Move_head( '#./test_shell/pipe_seq.sh', 'pipe_seq.sh' )

