varfile="$1"
name="$2"
block_num="$(wc -l "$varfile" | cut -f1 -d' ' )"

echo "void version_""$name""_init()"
echo "{"
echo "	mem_block cur_block;"
echo "	version_info cur_version;"
echo "	double_list version_head;"
echo "	shadow_type new_shadow;"
echo "	id_pair pair, tmp;"
echo "	int i;"
echo ""
echo "  new_shadow = hash_search( shadow_head, \"$name\", sizeof( shadow_type_s ) );"
echo "  new_shadow->struct_types = shadow_struct_""$name""_init( );"
echo "	version_head = ( double_list ) calloc( 1, sizeof( double_list_s ) + sizeof( version_info_s ) );"
echo "	if( version_head == NULL ){"
echo "		//print error info"
echo "		goto error;"
echo "	}"
echo "	cur_version = ( version_info )( version_head + 1 );"
echo "	cur_version->ref_num = 1;"
echo "	cur_version->block_num = $block_num;"
echo "	cur_version->order_id = ( addr_pair )calloc( 1, sizeof( id_pair_s ) * $block_num );"
echo "	if( cur_version->order_id == NULL ){"
echo "		goto error;"
echo "	}"
echo "	pair = cur_version->order_id;"
awk -v block_num="$block_num" -v name="$name" -F: 'BEGIN{
	id=1
	print "\tfor( i = 0, tmp = pair; i < "block_num"; i++, tmp++ ){"
	print "\t\ttmp->addr = malloc( sizeof( mem_block_s ) );"
	print "\t\tif( tmp->addr == NULL ){"
	print "\t\t\tgoto error;"
	print "\t\t}"
	print "\t}"
} 
{
	print "\tpair->id = "id";"
	print "\tcur_block = pair->addr;"
	print "\tcur_block->id = "id++";"
	print "\tcur_block->version = 0;"
	print "\tcur_block->virtual_addr = get_"name"_"$2"_addr();"
	print "\tcur_block->is_del = 0;"
	print "\tcur_block->is_root = 1;"
	print "\tcur_block->data = ( char * )get_"name"_"$2"_addr();"
	print "\tcur_block->type_num = get_"name"_"$2"_len();"
	print "\tcur_block->data_len = get_"name"_"$2"_size();"
	print "\tcur_block->type_id = find_type( new_shadow->struct_types, \""$1"\" );"
	print "\tif( cur_block->type_id < 0 ){"
	print "\t\tgoto error;"
	print "\t}"
	print "\tpair++;"
done
}' "$varfile"
echo "	cur_version->order_addr = sort_addr_id( cur_version->order_id, $block_num );"
echo "	if( cur_version->order_addr == NULL ){"
echo "		goto error;"
echo "	}"
echo "	new_shadow->init_version = version_head;"
echo "	return;"
echo "error:"
echo "	if( version_head != NULL ){"
echo "		if( cur_version->order_id != NULL){"
echo "			for( i = 0; i < cur_version->block_num; i++ ){"
echo "				if( cur_version->order_id[ i ].addr != NULL ){"
echo "					free( cur_version->order_id[ i ].addr );"
echo "				}else{"
echo "					break;"
echo "				}"
echo "			}"
echo "			if( cur_version->order_addr != NULL ){"
echo "				free( cur_version->order_addr );"
echo "			}"
echo "			free( cur_version->order_id );"
echo "		}"
echo "		free( version_head );"
echo "		version_head = NULL;"
echo "	}"
echo "}"
