Import( 'env' )

env.Append( LIBPATH = [ '#./moon_code' ] )
libs = env[ 'LIBS' ]
libs.insert( 0, 'moon_%s' % ( env['MOON_TARGET'] ) )
env.Replace( LIBS = libs )
objs = []
#dirs = [ 'debug', 'ring_buffer', 'sync', 'network', 'common'  ]
dirs = [ 'debug', 'ring_buffer', 'network', 'common'  ]
for subdir in dirs:
	o = SConscript( '%s/SConstruct' % ( subdir ) )
	objs.append( o )
lib = env.Library( 'moon_%s' % ( env['MOON_TARGET'] ), objs )
Return( 'lib' )
