Import( 'env' )

heads = env.Move_head( '#./moon_code/include_%s/ring_buffer.h' % ( env['MOON_TARGET'] ), 'ring_buffer.h' )
obj = env.Object( 'ring_buffer_%s' % ( env['MOON_TARGET'] ), 'ring_buffer.c' )
Depends( obj, heads )
Return( 'obj' )

