Import( 'env' )

objs = []
'''
env.Move_head( '#./moon_code/include_%s/moon_packet2.h' % ( env['MOON_TARGET'] ), [ 'moon_packet2.h' ] )
obj = env.Object( 'moon_packet2_%s' % ( env['MOON_TARGET'] ), 'moon_packet2.c' )
'''
env.Move_head( '#./moon_code/include_%s/moon_timer.h' % ( env['MOON_TARGET'] ), [ 'moon_timer.h' ] )
obj = env.Object( 'moon_timer_%s' % ( env['MOON_TARGET'] ), 'moon_timer.c' )
objs.append( obj )

env.Move_head( '#./moon_code/include_%s/moon_pthread_pool.h' % ( env['MOON_TARGET'] ), [ 'moon_pthread_pool.h' ] )
obj = env.Object( 'moon_pthread_pool_%s' % ( env['MOON_TARGET'] ), 'moon_pthread_pool.c' )
objs.append( obj )

env.Move_head( '#./moon_code/include_%s/common_socket.h' % ( env['MOON_TARGET'] ), [ 'common_socket.h' ] )
obj = env.Object( 'common_socket_%s' % ( env['MOON_TARGET'] ), 'common_socket.c' )
objs.append( obj )

env.Move_head( '#./moon_code/include_%s/moon_dns.h' % ( env['MOON_TARGET'] ), [ 'moon_dns.h' ] )
obj = env.Object( 'moon_dns_%s' % ( env['MOON_TARGET'] ), 'moon_dns.c' )
objs.append( obj )

Return( 'objs' )

